"""add disease table

Revision ID: b32d7749b838
Revises: 594b215c86f4
Create Date: 2024-11-12 12:14:59.278964

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b32d7749b838'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('disease',
    sa.Column('DiseaseID', sa.Integer(), nullable=False),
    sa.Column('DiseaseName', sa.String(), nullable=True),
    sa.Column('Symptoms', sa.String(), nullable=True),
    sa.Column('Prevention', sa.String(), nullable=True),
    sa.Column('Treatment', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('DiseaseID')
    )
    op.create_index(op.f('ix_disease_DiseaseID'), 'disease', ['DiseaseID'], unique=False)
    op.create_index(op.f('ix_disease_DiseaseName'), 'disease', ['DiseaseName'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_disease_DiseaseName'), table_name='disease')
    op.drop_index(op.f('ix_disease_DiseaseID'), table_name='disease')
    op.drop_table('disease')
    # ### end Alembic commands ###
